version: '3.8'

services:
  eduvision-app:
    build: .
    container_name: eduvision_app
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY:-""}
    volumes:
      - ./storage:/app/storage
    restart: unless-stopped
